### PR TITLE
feat: fish completion

### PR DESCRIPTION
**Pull request by matejvasek**

### CODE REVIEW

**Comment by matejvasek** [comment]
related https://github.com/spf13/cobra/pull/1247

**Review by zroubalik — APPROVED** [review]
LGTM

**Comment by matejvasek** [comment]
To make this work on `fish` version `3.0`  we need to  update the `cobra` dependency. @rhuss could it cause any problems in relation to `kn` package?

**Comment by rhuss** [comment]
Sorry for the late reply :) I don't expect any issues with the cobra dependency as cobra is movin very slowly anyway :)

**Pull request merged**
