### PR TITLE
feat!: remove create cli subcommand

### PR DESCRIPTION
**Pull request by lkingland**
Removes the `faas create` subcommand, renaming `init` to `create`.  #180

### CODE REVIEW

**Review by zroubalik — COMMENTED** [review]
Looking good, but docs should be changed as well.

**Comment by lance** [comment]
@lkingland any chance you can get the doc changes in before tomorrow's build?

**Comment by lkingland** [comment]
Unless I am missing some, the relatively small amount of docs referencing the `init` subcommand by name have now also been updated.

**Review by zroubalik — APPROVED** [review]
LGTM

**Comment by zroubalik** [comment]
@lkingland btw there are some related docs to be change as well in here: https://github.com/boson-project/functions

**Pull request merged**
