### PR TITLE
chore: ignore vscode files

### PR DESCRIPTION
**Pull request by zroubalik**
Signed-off-by: Zbynek Roubalik <zroubali@redhat.com>

### CODE REVIEW

**Review by lance — APPROVED** [review]

**Comment by lance** [comment]
Approved - but generally, I would expect IDE files to be in your global config.

**Comment by zroubalik** [comment]
@lance some settings are project related. For example debugger configuration etc

**Comment by lance** [comment]
> @lance some settings are project related. For example debugger configuration etc

In that case, do you think it would be good practice to share across the team and actually commit them, or is it specific to your personal dev environment?

**Comment by zroubalik** [comment]
> > @lance some settings are project related. For example debugger configuration etc
> 
> In that case, do you think it would be good practice to share across the team and actually commit them, or is it specific to your personal dev environment?

It is specific to each dev environmet, so commiting this would actually cause more problems, imho. But I am happy to commit that, if you want to.

**Comment by lance** [comment]
> > > @lance some settings are project related. For example debugger configuration etc
> > 
> > 
> > In that case, do you think it would be good practice to share across the team and actually commit them, or is it specific to your personal dev environment?
> 
> It is specific to each dev environmet, so commiting this would actually cause more problems, imho. But I am happy to commit that, if you want to.

No worries - I was just curious.

**Pull request merged**
