### PR TITLE
fix: image override

### PR DESCRIPTION
**Pull request by matejvasek**
resolves: #87

### CODE REVIEW

**Comment by lance** [comment]
@matejvasek can you help me understand why the call to `overrideImage()` is causing a failure in `Client.Create()`? Glancing through the code, it seems this should work so it's not obvious to me why there is a failure in the first place.

**Comment by matejvasek** [comment]
> @matejvasek can you help me understand why the call to `overrideImage()` is causing a failure in `Client.Create()`? Glancing through the code, it seems this should work so it's not obvious to me why there is a failure in the first place.

The `overrideImage()` functions creates the config file, but the `Create()` expects the directory to be empty. So maybe another possible fix would be switch order in which they are called. See linked issue.

**Comment by lance** [comment]
OK - I see now. When `Create()` calls `c.Initialize()` the `Initialize()` function calls `assertEmptyRoot()`. I don't really think switching the order would work, because where would you end up calling `overrideImage()`? This change makes more sense IMO.

**Pull request merged**
